#========================================= Drupal 9 StarterKit =============================================#
version: '3.5'
#____________________________________________ Named Volumes ________________________________________________#
volumes:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
  mysql-data:
  # Add These volume will increse speed on non linux hosts.
  # core:               # drupal core
  # vendor:             # php modules
  files:                # files
#______________________________________________ Networks ___________________________________________________#
networks:
  default:
    name: vega-${PROJECT_NAME}
#___________________________________________ YAML extensions _______________________________________________#
x-app-volumes: &app-volumes
    - files:${DOC_ROOT}/sites/default/files:delegated
    # - ./:/app:cached
    # - core:/app/web/core
    # - vendor:/app/vendor

    # Add any custom configuration files here

x-cli-volumes: &cli-volumes
    - ./:/app:delegated

x-app-envsfile: &app-envsfile .env

x-app-networks: &app-networks
  - default

#_______________________________________________ Services __________________________________________________#
services:
  #----------------------------- permission setter ------------------------------------#
  # Change mounted named volumes user from root(default) to continua.
  chown:
    image: "srijanlabs/php-cli:${PHP_VERSION}-10"
    container_name: ${PROJECT_NAME}_chown
    entrypoint: [ "bash", "-c"]
    command:
      - "chown -R continua:continua /app"
    user: root
    volumes: *app-volumes
  #---------------------------------- php cli -----------------------------------------#
  cli:
    image: "srijanlabs/php-cli:${PHP_VERSION}-10"
    container_name: ${PROJECT_NAME}_cli
    command: ["composer", "install", "--no-dev", "--prefer-dist", "--no-progress", "--no-suggest", "--no-interaction", "--optimize-autoloader"]
    user: continua
    working_dir: /app
    depends_on:
      - chown
    volumes:  *cli-volumes
    networks: *app-networks
    env_file:  *app-envsfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1 # Prevent composer from running out of memory
  #---------------------------------- drupal ------------------------------------------#
  drupal:
    image: srijanlabs/php-fpm-apache:${PHP_VERSION}-10-local
    container_name: ${PROJECT_NAME}_drupal
    depends_on:
      - mysql
    ports:
      - ${APPLICATION_PORT}:8080
    volumes: *app-volumes
    networks: *app-networks
    env_file:  *app-envsfile
  #------------------------------- database (mysql) -----------------------------------#
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks: *app-networks
  #------------------------------- blackfire -----------------------------------#
  # blackfire:
  #   image: blackfire/blackfire
  #   container_name: ${PROJECT_NAME}_blackfire
  #   ports:
  #     - "8707:8707"
  #   environment:
  #     # Exposes BLACKFIRE_SERVER_* environment variables from the host
  #     BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
  #     BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
  #   networks: *app-networks
#===========================================================================================================#
