version: '2.3'

x-vega-project:
  &vega-project drupal8

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile-cli
    image: *vega-project
    volumes:
      - .:/app

  php:
    build:
      context: .
      dockerfile: Dockerfile-fpm
      args:
        CLI_IMAGE: *vega-project
    ports:
      - 8080:8080
    depends_on:
      - cli
    ports:
      - 9000:9000

  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
      args:
        CLI_IMAGE: *vega-project
    ports:
      - 8080:8080
    volumes:
      - ./apache/vhost/app.conf:/etc/apache2/sites-enabled/000-default.conf 
    depends_on:
      - cli

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vega
      MYSQL_USER: vega
      MYSQL_PASSWORD: vega
      MYSQL_DATABASE: vega

  blackfire:
    image: blackfire/blackfire
    environment:
      # Exposes BLACKFIRE_SERVER_* environment variables from the host
      BLACKFIRE_SERVER_ID: 1ce028d2-644b-4451-9eaa-7f142f4151cc
      BLACKFIRE_SERVER_TOKEN: 91471c1696eefc49bf4a397ddafc457a49825c57ccbd45916a64e23aa106add0

volumes:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
  data: